<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rasmalai Cake_product-rating m-0</name>
   <tag></tag>
   <elementGuidId>260bfc8e-caf1-4afb-b20d-23e58d292c1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shop-1']/div/div[2]/div/a/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20cca662-4bf7-434e-a2fd-d14a6d85abda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-rating m-0</value>
      <webElementGuid>2e889f61-9334-44c0-87a0-ea805f8d2aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shop-1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 col-lg-3 px-1&quot;]/div[@class=&quot;product-wrap mb-15 scroll-zoom card product-div border-0 rounded-0&quot;]/a[@class=&quot;card-body py-1 px-1&quot;]/div[@class=&quot;product-content text-center text-md-left  pt-2 pl-md-2&quot;]/div[@class=&quot;product-rating m-0&quot;]</value>
      <webElementGuid>63da5cc4-5d90-427e-a8d4-be4ac05ea6fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shop-1']/div/div[2]/div/a/div[2]/div</value>
      <webElementGuid>4014005d-1c5f-4d80-a34b-8117664d53a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div[2]/div</value>
      <webElementGuid>f941c394-75e4-47f8-913b-eb8ade8087de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
