<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Rasmalai Cake</name>
   <tag></tag>
   <elementGuidId>8ee4247c-d884-466b-9b5e-a2a761415896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shop-1']/div/div[2]/div/a/div[2]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>6aae04a7-8e69-430d-9757-eee7f15d4300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prd-catg-title</value>
      <webElementGuid>9c3dac10-906a-4b88-b338-ad34475d4d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rasmalai Cake</value>
      <webElementGuid>2f1f7861-ad4a-4cbf-bf7a-ffa0eda6bf09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shop-1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 col-lg-3 px-1&quot;]/div[@class=&quot;product-wrap mb-15 scroll-zoom card product-div border-0 rounded-0&quot;]/a[@class=&quot;card-body py-1 px-1&quot;]/div[@class=&quot;product-content text-center text-md-left  pt-2 pl-md-2&quot;]/h3[@class=&quot;prd-catg-title&quot;]</value>
      <webElementGuid>2fb878ef-a3e1-49ad-83e6-2cef6e352841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shop-1']/div/div[2]/div/a/div[2]/h3</value>
      <webElementGuid>f68e0421-bb8e-4370-83aa-c7a955e04016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div[2]/h3</value>
      <webElementGuid>25ad0073-0d61-48ab-a3f8-9ce0867d8ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Rasmalai Cake' or . = 'Rasmalai Cake')]</value>
      <webElementGuid>416a007d-b8a1-482b-a88b-4bf93c6a2085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
