<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__396cs4</name>
   <tag></tag>
   <elementGuidId>a085f30b-76bf-4a2d-b07d-5974bcc3ae92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div[5]/div[2]/div[13]/div/div[2]/div/div/div/div/div[3]/div/div/a/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4afff1ec-5ae6-4489-97a3-cafd7ef4d379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>658a4cbd-d5b4-480a-9e8f-6ec1673ce70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_396cs4</value>
      <webElementGuid>12830b00-0e4c-4130-ba13-c5ece7b524ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>realme C53 (Champion Gold, 128 GB)</value>
      <webElementGuid>37c3d1d2-c883-4392-8640-0e4b46f87170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/h/h/d/-original-imags487gaqqhcea.jpeg?q=70</value>
      <webElementGuid>6b9deddf-9160-41a5-b316-d65364f66953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg col-10-12&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;_3E8aIl Zic51i&quot;]/div[2]/div[@class=&quot;_3ZYowz _2CfYpZ&quot;]/div[@class=&quot;mYI3GX&quot;]/div[@class=&quot;_2hKRMr _2CfYpZ&quot;]/div[@class=&quot;_37K3-p&quot;]/div[@class=&quot;_3YgSsQ&quot;]/div[@class=&quot;_2n7i6c&quot;]/div[@class=&quot;_4ddWXP _3BCh3_&quot;]/a[@class=&quot;_2rpwqI&quot;]/div[@class=&quot;_28_T72&quot;]/div[1]/div[@class=&quot;CXW8mj&quot;]/img[@class=&quot;_396cs4&quot;]</value>
      <webElementGuid>59c39e69-c0db-4a2a-8573-0f9043cbe150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div[5]/div[2]/div[13]/div/div[2]/div/div/div/div/div[3]/div/div/a/div/div/div/img</value>
      <webElementGuid>bc59f93f-3463-4399-8320-1f3393671dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='realme C53 (Champion Gold, 128 GB)']</value>
      <webElementGuid>0b79fb46-e968-4ee5-925a-858e173f0565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/div/div/div/div/div[3]/div/div/a/div/div/div/img</value>
      <webElementGuid>0c92def0-37f6-47af-8fa5-09fa9acdc128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'realme C53 (Champion Gold, 128 GB)' and @src = 'https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/h/h/d/-original-imags487gaqqhcea.jpeg?q=70']</value>
      <webElementGuid>734ce2dd-be91-4f5a-9be5-23837a763033</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
