<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>7d3eb0d7-e996-45ca-9e27-c0f54818fa22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._1YokD2._3Mn1Gg.col-10-12 > div._1AtVbE.col-12-12 > div._3ChZRr._1rs5Pv > div._24OVr- > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>ffc3a432-1cef-4170-85e5-28df2502d0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14.6</value>
      <webElementGuid>a9f8e747-b2e4-440a-8588-435e6102887d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>39119336-c54e-4dd3-a40f-e8559c9f78f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 16 27</value>
      <webElementGuid>89a8b6e1-7f6e-46a2-b9c1-6b429576aa84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>1672f97c-6f0b-45cf-a1bc-148bf577a946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg col-10-12&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;_3ChZRr _1rs5Pv&quot;]/div[@class=&quot;_24OVr-&quot;]/svg[1]</value>
      <webElementGuid>090cb8ea-b27e-41dd-be84-7e98ec3f9a41</webElementGuid>
   </webElementProperties>
</WebElementEntity>
