<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No More Products</name>
   <tag></tag>
   <elementGuidId>9f96a006-400e-4233-b15b-5419de189feb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loader_message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loader_message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a0a7d69-cda2-4db8-928d-86560369da9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loader_message</value>
      <webElementGuid>5cbc02d2-38b0-4f4f-8371-f86105e1bd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No More Products.</value>
      <webElementGuid>05b81aef-c0d1-4054-af64-878545a1e7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loader_message&quot;)</value>
      <webElementGuid>bb84329b-f031-4fbe-b3a9-53a603e6b36c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='loader_message']</value>
      <webElementGuid>a9e85334-b229-4e24-9ec1-e9c999135c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shop-1']/div[3]/div[3]</value>
      <webElementGuid>40a1586f-d08c-42b6-b60b-20d25ee055bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>b7d091a4-9a14-4bbc-9972-fdb2b8b903ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'loader_message' and (text() = 'No More Products.' or . = 'No More Products.')]</value>
      <webElementGuid>fafafff7-0b3e-4d9c-8b21-63c95095c3f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
