<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No More Products</name>
   <tag></tag>
   <elementGuidId>009209fb-91c2-4687-a806-df7379e4ea16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loader_message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loader_message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>964b5fd4-8ef5-42d2-a575-48b1d839eddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loader_message</value>
      <webElementGuid>6cefe339-6e54-4557-b8d1-dc8109d1f865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No More Products.</value>
      <webElementGuid>28900490-50cf-4e3c-b5c9-fbd8ba726b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loader_message&quot;)</value>
      <webElementGuid>9d85b7c5-2e6c-44ef-8c14-40d95c39239a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='loader_message']</value>
      <webElementGuid>1ce4d562-9f6d-4af9-853e-42ac4264306d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shop-1']/div[3]/div[3]</value>
      <webElementGuid>befcabe6-8553-45b7-9adb-34726fc1f045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>be72c9a2-451e-4705-8f25-78bb8a2ed9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'loader_message' and (text() = 'No More Products.' or . = 'No More Products.')]</value>
      <webElementGuid>407f4536-048b-41e2-8e44-c78c9c1c2cd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
