<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select city</name>
   <tag></tag>
   <elementGuidId>1e742c0c-6157-4ca3-a539-ccb5debc0a7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._8Phu0v</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div[2]/div[3]/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d89e77b-7bcf-454e-be95-e1edf6a89db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_8Phu0v</value>
      <webElementGuid>6484e745-a994-43c3-8a46-5b1fee4a67e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select city</value>
      <webElementGuid>16f43e11-bd70-4ece-b33e-c7fb1a744abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_1kfTjk&quot;]/div[@class=&quot;_2nQkPF _1rH5Jn&quot;]/div[@class=&quot;_2Xfa2_&quot;]/div[@class=&quot;go_DOp _1ASpQe&quot;]/div[@class=&quot;_2yTL60&quot;]/div[@class=&quot;_1psGvi _3w81sF&quot;]/div[1]/div[@class=&quot;_8Phu0v&quot;]</value>
      <webElementGuid>2c6d4d0c-b20a-4c70-84ab-4599f4e74e57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[2]/div[3]/div[2]/div/div/div</value>
      <webElementGuid>c042b64b-40b1-481f-8006-3493bb550846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div</value>
      <webElementGuid>85626055-84c7-437b-aef8-8c1e3967d451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select city' or . = 'Select city')]</value>
      <webElementGuid>c93c5b09-9c5e-4ad5-9327-f5a9452b11e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
