<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg__2Dwidy</name>
   <tag></tag>
   <elementGuidId>18e02b5b-1fba-4006-850d-067a776ef7f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg._2Dwidy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>fb7b8f2d-6dc7-4a5d-9a81-97c35fbee5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>4.7</value>
      <webElementGuid>c3bbb71f-11e4-496f-9eff-826e49c8e151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>3be093db-8bef-4f04-8537-37282f5317fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 16 27</value>
      <webElementGuid>13a5f4b0-803c-4078-8b35-cb241792bea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>4cf6cc6f-7ff7-44a8-8a4b-42ec3d2d1653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2Dwidy</value>
      <webElementGuid>7f91e2a8-5f50-428d-aa4f-bd4bdd9535c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_1kfTjk&quot;]/div[@class=&quot;_2nQkPF _1rH5Jn&quot;]/div[@class=&quot;_2Xfa2_&quot;]/div[@class=&quot;go_DOp _1ASpQe&quot;]/div[@class=&quot;_2yTL60&quot;]/svg[@class=&quot;_2Dwidy&quot;]</value>
      <webElementGuid>266eef35-b389-4463-b5bb-b82bbf66352b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
