<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_in</name>
   <tag></tag>
   <elementGuidId>c20b3a58-c497-493a-8824-b7d0f16412f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-logo-sprites</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-logo-sprites']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e76ea726-a358-495e-8107-4dfec40f45cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ref=nav_logo</value>
      <webElementGuid>69581efa-b428-4f66-b09d-90424d9d724d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-logo-sprites</value>
      <webElementGuid>11ebaf8f-5c03-4d5a-9143-f6fdc7a950ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-logo-link nav-progressive-attribute</value>
      <webElementGuid>f317a7a8-36af-43b2-8e0a-61fc032862c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Amazon.in</value>
      <webElementGuid>aa856b68-a550-46d2-bb78-127d9cce4c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      
      
      .in
    </value>
      <webElementGuid>ecab1617-30dc-4f66-a399-9eea83e44a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-logo-sprites&quot;)</value>
      <webElementGuid>591aff3e-72f1-4c2d-9c63-05a5eeb14186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-logo-sprites']</value>
      <webElementGuid>f35551ed-2170-4b7b-9e27-3d71627ab700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-logo']/a</value>
      <webElementGuid>c45abbc1-02fe-4a5c-9627-7f6f73245309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ref=nav_logo')]</value>
      <webElementGuid>7b0342af-84eb-46cd-be6f-1f62cd7dee45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>9a3d353b-5160-4cc8-9d08-08a27f47763b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ref=nav_logo' and @id = 'nav-logo-sprites' and (text() = '
      
      
      .in
    ' or . = '
      
      
      .in
    ')]</value>
      <webElementGuid>23bcc3f2-c0e5-4d66-870d-cb2818299540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
