<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_number</name>
   <tag></tag>
   <elementGuidId>1b6ebe22-2866-4220-87cb-84477f126efc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;number&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28abcd7a-8837-4988-8426-9954029278b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Purchasing for:</value>
      <webElementGuid>cc11a3e2-3b9f-402f-ab65-053c93751423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>dfca1b14-3a58-4fd8-baca-399c842b3278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;application--wrap&quot;]/div[@class=&quot;layout row wrap&quot;]/div[@class=&quot;flex inquiry-form xs12 md6&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;offer-box form-card v-card v-sheet theme--light elevation-4&quot;]/div[2]/div[@class=&quot;v-card__text&quot;]/div[1]/div[@class=&quot;v-card__text pt-0&quot;]/div[@class=&quot;v-input currency-field mb-2 v-text-field v-text-field--prefix v-input--has-state v-input--is-focused theme--light error--text&quot;]/div[@class=&quot;v-input__control&quot;]/div[@class=&quot;v-input__slot&quot;]/div[@class=&quot;v-text-field__slot&quot;]/input[1]</value>
      <webElementGuid>25ff457b-b6ab-435c-a9a3-40c1ce3fa7e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='number']</value>
      <webElementGuid>a1846eef-5000-4c4e-a5bd-9aa13581d1d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/form/div/div[2]/div/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>e988e8d0-b64f-4f06-9866-657164ca6fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>3bda03fe-715b-453e-a1b7-1c4b5751d659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>32e1839a-35dd-4ea9-825c-f5108591da50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
