<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Im not a robot</name>
   <tag></tag>
   <elementGuidId>90f4158c-05ee-4839-aca0-d1d6ff90d203</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recaptcha-anchor-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='recaptcha-anchor-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0d4fa0c5-f813-47d9-a21e-a8f42b9c941e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-anchor-center-item rc-anchor-checkbox-label</value>
      <webElementGuid>16aa4b54-f636-4fff-bb7a-996f5626fbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8fa26674-a84f-4cfa-bd81-9049dfda1ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>59adbb67-b171-4e1c-9f24-3cdbf1efef20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recaptcha-anchor-label</value>
      <webElementGuid>8f9cba36-fdaf-4bce-8e3f-977aa1bbf7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I'm not a robot</value>
      <webElementGuid>763d78ab-ecc7-4fcf-b98c-489f098a3888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-anchor-label&quot;)</value>
      <webElementGuid>d85e0770-928a-4f6b-a722-e8e34337b3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Justbake_manual/Page_Justbake.com is for sale  Bodis.com - Smart Domain Monetization/iframe_Required_a-ghlya4i2onw1</value>
      <webElementGuid>7da14a89-2898-46ba-8f81-7c23fa37f8b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='recaptcha-anchor-label']</value>
      <webElementGuid>5716ddad-aeca-4dba-951d-b1ff2cab1519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-anchor-container']/div[3]/div[2]/div/label</value>
      <webElementGuid>7c5248c3-08da-457d-83f1-0deed88029cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>ab04d24f-02ba-4cfc-985d-1e4bdef1188b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'recaptcha-anchor-label' and (text() = concat(&quot;I&quot; , &quot;'&quot; , &quot;m not a robot&quot;) or . = concat(&quot;I&quot; , &quot;'&quot; , &quot;m not a robot&quot;))]</value>
      <webElementGuid>40c6391c-f8fc-4018-8a59-4bc086bc7217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
