<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>3a2ae614-7695-4949-974e-d59478bf2d11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.v-btn.v-btn--round.theme--light.primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6627ff2-663e-4bd3-92f4-7ae9613b2855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3ac426f2-d8d2-4350-836f-19c1c5fe1021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--round theme--light primary</value>
      <webElementGuid>2bd64582-6e82-433a-b159-e0624ecbd3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                      Submit
                    </value>
      <webElementGuid>2fcd2136-82a5-4cc6-bab1-9072846c3c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;application--wrap&quot;]/div[@class=&quot;layout row wrap&quot;]/div[@class=&quot;flex inquiry-form xs12 md6&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;offer-box form-card v-card v-sheet theme--light elevation-4&quot;]/div[2]/div[@class=&quot;v-card__text&quot;]/div[@class=&quot;d-flex justify-space-between&quot;]/div[@class=&quot;text-xs-center mt-3 mb-4&quot;]/button[@class=&quot;v-btn v-btn--round theme--light primary&quot;]</value>
      <webElementGuid>40fe40a1-1f70-463a-9cdc-6e592c2fac58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>c4093458-a196-4b49-b6d8-554dcc7108de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/form/div/div[2]/div/div[2]/div/button</value>
      <webElementGuid>a2ed8116-502a-4bed-9ed6-85f0d10b38c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9c88879c-c8d9-46d8-863a-55cfc31f2ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                      Submit
                    ' or . = '
                      Submit
                    ')]</value>
      <webElementGuid>74e4e355-7aaa-43f9-bde4-5420d4248a9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
