<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_number</name>
   <tag></tag>
   <elementGuidId>0732d74d-a3d7-48d3-9ad6-8ba3054a3cfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;number&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2a324e0-0a66-4ec6-af59-a58525e67e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Purchasing for:</value>
      <webElementGuid>0c1531e3-5d40-4073-9777-18a52dc71cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>bec141ef-78e4-4134-8a63-edea516ea6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;application--wrap&quot;]/div[@class=&quot;layout row wrap&quot;]/div[@class=&quot;flex inquiry-form xs12 md6&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;offer-box form-card v-card v-sheet theme--light elevation-4&quot;]/div[2]/div[@class=&quot;v-card__text&quot;]/div[1]/div[@class=&quot;v-card__text pt-0&quot;]/div[@class=&quot;v-input currency-field mb-2 v-text-field v-text-field--prefix v-input--is-focused theme--light primary--text&quot;]/div[@class=&quot;v-input__control&quot;]/div[@class=&quot;v-input__slot&quot;]/div[@class=&quot;v-text-field__slot&quot;]/input[1]</value>
      <webElementGuid>ba40d7d1-26a4-4414-9d11-fc216540c108</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='number']</value>
      <webElementGuid>30a2499c-64c9-436e-85e0-30ca29a19be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/form/div/div[2]/div/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>2f459eb8-ac64-4708-b209-1480904d423e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>d2a4aeb6-1d10-4fe7-9371-cfa8a86c100d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>3ab703f7-b20a-405a-a141-f706e572e8de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
