<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>38ab8236-d139-41dd-bcaf-54d5f4fbcf1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;New Launches from Mobile, Electronics &amp; more&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navSwmHoliday']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d1f9c1f-864e-4ae1-9f45-1a1469ca5c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>New Launches from Mobile, Electronics &amp; more</value>
      <webElementGuid>84449e9c-88ad-4666-973f-08995ac0f08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/G/31/Gateway_IN/testing/NewLaunches_400x39._CB593645585_.jpg</value>
      <webElementGuid>5df54dec-4bb7-4524-a871-e843bda3d285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navSwmHoliday&quot;)/a[@class=&quot;nav-imageHref&quot;]/img[1]</value>
      <webElementGuid>d5dc9076-cc98-472f-905a-311f504f3c25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navSwmHoliday']/a/img</value>
      <webElementGuid>8ae64a7d-aad0-4c61-bf1d-084e310c601b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='New Launches from Mobile, Electronics &amp; more']</value>
      <webElementGuid>e8a679e4-e19e-498c-b9ee-5a37aa38cf42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>d763415f-3d9a-44ff-b015-7c77fa338e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'New Launches from Mobile, Electronics &amp; more' and @src = 'https://m.media-amazon.com/images/G/31/Gateway_IN/testing/NewLaunches_400x39._CB593645585_.jpg']</value>
      <webElementGuid>e2dadae7-3170-4f3a-802d-50fa46715cb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
