<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_q</name>
   <tag></tag>
   <elementGuidId>aec8d802-1fb4-4fef-9dce-bb83cf69a5ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;q&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='q']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d275f748-56cf-4935-8d6f-d06d86051c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Pke_EE</value>
      <webElementGuid>bedc49c6-88a3-4096-b534-54e7e76abe8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>474a8c75-744a-4898-aa01-a4a18533b7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search for Products, Brands and More</value>
      <webElementGuid>5cbb5547-f016-46f4-b866-60fd2f26dea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>51ddb7ca-88ac-489d-b319-5e316bbaae5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>15159027-a363-42c9-9b97-9a65f5c5fc43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for Products, Brands and More</value>
      <webElementGuid>b22a9c8e-f4df-4d5b-9c2d-3815e802f636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;q8WwEU&quot;]/div[@class=&quot;_3zsGrb&quot;]/div[@class=&quot;_2-LWwB&quot;]/div[1]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;_1ui5b4&quot;]/div[@class=&quot;_2nl6Ch&quot;]/div[@class=&quot;_2NhoPJ&quot;]/header[@class=&quot;_3EOQ5Q&quot;]/div[@class=&quot;_3ZqtNW&quot;]/div[@class=&quot;_3NorZ0 _3jeYYh&quot;]/form[@class=&quot;_2rslOn header-form-search&quot;]/div[@class=&quot;_1sFryS _2alaMB&quot;]/div[@class=&quot;_2SmNnR&quot;]/input[@class=&quot;Pke_EE&quot;]</value>
      <webElementGuid>a95e6a59-c4cb-4431-b87d-0a79a6744ec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='q']</value>
      <webElementGuid>c550e05e-92d7-40d2-ab01-732dc4c84688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div/div/header/div/div[2]/form/div/div/input</value>
      <webElementGuid>12eb483c-d791-4551-8cfc-9b535471bfb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>783b6dc7-837c-4af2-b152-150a8ce1b925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'Search for Products, Brands and More' and @name = 'q' and @placeholder = 'Search for Products, Brands and More']</value>
      <webElementGuid>d55ff989-cd26-4782-91d1-e4afd9e5d4dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
