<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Studio</name>
   <tag></tag>
   <elementGuidId>756a613f-a587-4ba3-9811-46fad66148ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='desktop-header-cnt']/div[2]/nav/div/div[6]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df68987e-1775-49e0-9a89-2a4a2827229e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/studio/home</value>
      <webElementGuid>a2c032ff-3780-4768-b257-676e0d0cb7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5b4409d6-f701-4243-b4bd-eacd0d763001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>studio</value>
      <webElementGuid>a72ab8bb-ee71-4842-a3c0-7b7fddf68671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>#ff3f6c</value>
      <webElementGuid>88887736-7e70-44d0-86ba-6d9240fc69b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>navElements</value>
      <webElementGuid>8a9470aa-f688-4486-a843-1f8a6da73a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-main</value>
      <webElementGuid>b3fa53cb-6c11-4683-90e4-bc5fd2777b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>838</value>
      <webElementGuid>8b6c7dd9-4329-4049-b3e6-c8791e6ac79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Studio</value>
      <webElementGuid>5872b8b8-dae1-4ffe-8d51-6428f32797c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-header-cnt&quot;)/div[@class=&quot;desktop-bound&quot;]/nav[@class=&quot;desktop-navbar&quot;]/div[@class=&quot;desktop-navLinks&quot;]/div[@class=&quot;desktop-navContent&quot;]/div[@class=&quot;desktop-navLink&quot;]/a[@class=&quot;desktop-main&quot;]</value>
      <webElementGuid>b778fed9-9b11-4485-b40d-a03f722c14c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='desktop-header-cnt']/div[2]/nav/div/div[6]/div/a</value>
      <webElementGuid>416ffca9-40f1-4874-8784-b83745d33456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Studio')]</value>
      <webElementGuid>a65d96df-9d5b-4ca2-be2b-9026b81a67e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/studio/home')]</value>
      <webElementGuid>b9e1f72f-479c-494c-abf7-1fdf17e7eb75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a</value>
      <webElementGuid>0fa78dc5-7589-4789-8d43-7e851b8e7593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/studio/home' and (text() = 'Studio' or . = 'Studio')]</value>
      <webElementGuid>2c8bd047-da07-452c-8914-65e683433b56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
