<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bag_desktop-searchBar</name>
   <tag></tag>
   <elementGuidId>f18d7ff8-c8d0-4d72-94db-0a845232dfee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.desktop-searchBar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3db96972-c5f8-4160-8254-74e4c3fd2c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for products, brands and more</value>
      <webElementGuid>ad519e97-88c4-4446-87a3-471e04d36a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-searchBar</value>
      <webElementGuid>9ea5f099-4597-4e49-8700-75c2ccf36dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>907</value>
      <webElementGuid>f7699a5b-f3aa-40a2-9174-cbc76a8a0ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-header-cnt&quot;)/div[@class=&quot;desktop-bound&quot;]/div[@class=&quot;desktop-query&quot;]/input[@class=&quot;desktop-searchBar&quot;]</value>
      <webElementGuid>f8750b20-ab92-42c6-8ac6-b031c02e6302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>0f1732dd-ce1f-4fcd-9d84-e99e8fe34c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='desktop-header-cnt']/div[2]/div[3]/input</value>
      <webElementGuid>22957c11-3a9c-4ab5-ae82-5ebbdbfe81b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8a43c589-d20b-46e3-8787-3db04a50198f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search for products, brands and more']</value>
      <webElementGuid>621d35e0-a0e4-410c-beb9-beb1e2e4df20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
