<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Profile</name>
   <tag></tag>
   <elementGuidId>b76dab79-98bf-4fbf-8ccb-9b7b8ae83005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.desktop-userTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='desktop-header-cnt']/div[2]/div[2]/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b6ce7b81-b872-4304-aa29-2ca240da2a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-userTitle</value>
      <webElementGuid>09ac1d01-ac60-4598-ba80-d59916a7abc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>856</value>
      <webElementGuid>e1199620-64d2-48f8-9602-0931b5dd78a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profile</value>
      <webElementGuid>750f9530-82a1-4a85-82e3-740cb1284042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-header-cnt&quot;)/div[@class=&quot;desktop-bound&quot;]/div[@class=&quot;desktop-actions&quot;]/div[@class=&quot;desktop-user&quot;]/div[@class=&quot;desktop-userIconsContainer&quot;]/span[@class=&quot;desktop-userTitle&quot;]</value>
      <webElementGuid>da7adb1a-55d0-44b5-adaf-c85ade50795c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='desktop-header-cnt']/div[2]/div[2]/div/div/span[2]</value>
      <webElementGuid>f6f87193-991a-4b96-8e33-fce39265ccd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>3c1a5ea4-ad3b-4df0-a24d-cf10889fa70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Profile' or . = 'Profile')]</value>
      <webElementGuid>32dad3dc-1822-4e0e-aec2-75ec46cb28da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
