<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bag</name>
   <tag></tag>
   <elementGuidId>004f126d-0c7e-4eb0-bf6a-00aac6b8f104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.desktop-cart > span.desktop-userTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='desktop-header-cnt']/div[2]/div[2]/a[2]/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c474b1ce-b23f-4074-beab-d7ba2abb9db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-userTitle</value>
      <webElementGuid>9816683c-44de-4b24-893e-47b7d78d9b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>905</value>
      <webElementGuid>34e43b41-136e-4e28-995d-cd9644ce5c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bag</value>
      <webElementGuid>5a3ffba8-83f2-4cd9-a3c3-4c1522cc37d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-header-cnt&quot;)/div[@class=&quot;desktop-bound&quot;]/div[@class=&quot;desktop-actions&quot;]/a[@class=&quot;desktop-cart&quot;]/span[@class=&quot;desktop-userTitle&quot;]</value>
      <webElementGuid>c19d2241-d059-496a-b9d7-902f6a1fee3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='desktop-header-cnt']/div[2]/div[2]/a[2]/span[3]</value>
      <webElementGuid>f07edbce-9381-40ae-bd83-f1bd0629a631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>c758206a-4f14-489c-b54f-78ca0027278b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Bag' or . = 'Bag')]</value>
      <webElementGuid>72c746f2-0aa9-485c-b890-c33ff0ff74c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
