<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__18u87m _3WuvDp</name>
   <tag></tag>
   <elementGuidId>5793438e-4641-496b-b4d9-52e523214b36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input._18u87m._3WuvDp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0cdea57-68b5-4652-a06d-7d61965edeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>41345710-1788-4ea8-8f3b-23c411acabdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>740eb0b1-29be-4b28-bd41-5d1c282eb8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_18u87m _3WuvDp</value>
      <webElementGuid>42331c98-df3e-4c5c-b416-2b52caa24c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focusvisible-polyfill</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ecefb1b0-2961-4c03-8dfd-2d0e2373c262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;useInterFont en-fonts-loaded&quot;]/body[@class=&quot;fk-modal-visible&quot;]/div[@class=&quot;fbDBuK _3CYmv5&quot;]/div[@class=&quot;JFPqaw&quot;]/div[@class=&quot;_17UxrZ&quot;]/div[@class=&quot;_1E5Hij&quot;]/div[@class=&quot;_3skCyB&quot;]/div[1]/form[1]/div[@class=&quot;_22Dgdy _29BEA8&quot;]/input[@class=&quot;_18u87m _3WuvDp&quot;]</value>
      <webElementGuid>6972cc36-2e7c-45af-8f21-d2e888020989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>f0e213e6-48b5-4b08-aaa4-003a2b3e91ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/input</value>
      <webElementGuid>44fdc293-88a3-4cf2-9e24-ebaaf46bd55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>50bffb7d-f68e-414c-b8cb-6ffcde6a5dbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
