<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>3347b8c0-0ac4-4866-adef-8b9e69247b97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span._30XB9F</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c6cca9cc-e5d1-464a-9ac8-30cbbb7c9889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b1fbd946-e4a3-4677-ad1a-a2eb6209f507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_30XB9F</value>
      <webElementGuid>c56404ba-a2d0-4066-b870-bf02bc69cb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>✕</value>
      <webElementGuid>0a726ea7-6105-443e-93c1-f1406707ff1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;useInterFont en-fonts-loaded&quot;]/body[@class=&quot;fk-modal-visible&quot;]/div[@class=&quot;fbDBuK _3CYmv5&quot;]/div[@class=&quot;JFPqaw&quot;]/span[@class=&quot;_30XB9F&quot;]</value>
      <webElementGuid>36dba82a-c96c-4d89-be1f-ad30cf594206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>278a6c5b-7041-44ec-b71d-b4835745f840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '✕' or . = '✕')]</value>
      <webElementGuid>d3ae22db-7093-4a15-b3f6-9efadb97d728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
